import React from 'react'

function Section2() {
  return (
   <div className='h-screen flex justify-center items-center '>
   <div className='max-w-[1556px] w-full border '>
   <p className='uppercase font-haasRegular'>wedding</p>
   <h1 className='text-[#2C2216] text-[60px] w-[1000px] font-recklessRegular leading-[55px] mt-[17px] mb-[48px]'>
   EVENTS ARE CRUCIAL FOR ENHANCING BRAND AWARENESS, OFFERING EXCLUSIVE CHANCES TO SHOWCASE IDEAS, PRODUCTS, AND SERVICES INTIMATELY.
   </h1>
   <p className='text-[#2C2216] text-[16px] font-haasRegular w-[766px] leading-[20px]'>ALIQUAM SIT AMET TELLUS FERMENTUM, SEMPER ORCI FINIBUS, ULTRICES ORCI. MAECENAS FAUCIBUS FEUGIAT TINCIDUNT. PELLENTESQUE NON LEO CONGUE, DICTUM MAGNA AC, LAOREET ERAT. NUNC VENENATIS TRISTIQUE ENIM, ET FINIBUS FELIS ULTRICIES A. SUSPENDISSE AC VIVERRA ORCI, ET CONSEQUAT DOLOR. FUSCE CONVALLIS EST EU FELIS VENENATIS, AT VIVERRA EST SEMPER. PROIN ULTRICIES FELIS NEC ARCU VESTIBULUM, NON CURSUS DUI MOLLIS. NULLAM RISUS DIAM, VOLUTPAT NON CURSUS EU, PRETIUM VEL ORCI. ORCI VARIUS NATOQUE PENATIBUS ET MAGNIS DIS PARTURIENT MONTES, NASCETUR RIDICULUS MUS. ALIQUAM ALIQUAM, LECTUS AT VESTIBULUM TINCIDUNT, ENIM SEM VESTIBULUM ERAT, ET FEUGIAT VELIT EROS VITAE URNA. PELLENTESQUE HABITANT MORBI TRISTIQUE SENECTUS ET NETUS ET MALESUADA FAMES AC TURPIS EGESTAS.</p>
   </div>
   </div>
  )
}

export default Section2